### PR TITLE
Making the middle fork even before I make a bunch of massive updates.

### PR DESCRIPTION
**Pull request by DrakDv**
Hello! I am going to be using your fork because I admire map developers and I value the fix you have done. I am going to be maintaining my fork with PaperMC/Paper either until the world explodes or they concede to the argument of unwanted chat signing.

Up to you. :)

Good luck. And sleep well.

### CODE REVIEW

**Comment by Nico314159** [comment]
Hi, thanks a lot for noticing this! I accept this offer and I am honored that you would like to build off of my work.

**Comment by Nico314159** [comment]
> I admire map developers and I value the fix you have done

In fact, if you happen to know about other mapmaking features that Paper breaks, I suggest that we could work together to include fixes to them as well (although I understand it is not the main focus of your fork)

**Comment by DrakDv** [comment]
Yeah. Maybe I could add you to the github org that I am doing this with? Up to you. :)

**Comment by Nico314159** [comment]
> Yeah. Maybe I could add you to the github org that I am doing this with? Up to you. :)

That would be great, please do!

**Comment by Nico314159** [comment]
@Drakified For some weird reason, GitHub UI decided to stop letting me sync the fork while pull requests were open [idk why] so I had to close & reopen this. Are your plans here still on or did something happen?

**Comment by DrakDv** [comment]
Life got busy man. :P LOL. I might work on it some more though. Also, paper went back on what they said and actually allowed people to choose if they wanted chat signing.

**Comment by Nico314159** [comment]
> Life got busy man. :P LOL. I might work on it some more though. Also, paper went back on what they said and actually allowed people to choose if they wanted chat signing.

Okay, sounds good. Do you mind if I close this pull request then?

**Pull request closed without merging**
